# Generated by Django 5.0.7 on 2024-08-02 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_desc_alter_product_inventory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='inventory',
            new_name='quantity',
        ),
    ]
